root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -tags integration -o ./tmp/api ./cmd/api"
  bin = "./tmp/api"
  delay = 500
  poll = true
  poll_interval = 500

  include_ext = ["go", "yaml", "yml", "env", "toml"]
  exclude_dir = ["tmp", "bin", ".git", "docker"]
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true