services:
  api:
    build: 
      context: .
      dockerfile: docker/dev/Dockerfile
    container_name: go-skeleton-app
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "8081:8081"
    networks:
      - go-skeleton-network

  mysql:
      image: mysql:latest
      container_name: mysql-container
      environment:
        MYSQL_ROOT_PASSWORD: my-secret-pw
        MYSQL_DATABASE: my_database
        MYSQL_USER: app_user
        MYSQL_PASSWORD: app_pwd
      ports:
        - "3306:3306"
      volumes:
        - mysql-data:/var/lib/mysql
      networks:
      - go-skeleton-network
  
  db_postgres:
      image: pgvector/pgvector:pg16
      container_name: postgres-container
      volumes:
          - postgres-data:/var/lib/postgresql
      environment:
          POSTGRES_PASSWORD: postgres_pwd
          POSTGRES_USER: postgres_usr
          POSTGRES_DB: postgres
      ports:
          - "5433:5432"
      networks:
          - go-skeleton-network
  
networks:
  go-skeleton-network:
    driver: bridge

volumes:
  mysql-data:
  postgres-data: